- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  setPreference: false
  playTimeTracker: JobParamedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400
    - !type:OverallPlaytimeRequirement
      time: 21600
  startingGear: ParamedicGear
  icon: "Paramedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Service
  - External
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: MedicalTraining

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltParamedicFilled
  innerclothingskirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
