using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.SimpleStation14.Documentation.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class DocsWindow : DefaultWindow
    {
        public DocsWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
