- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 14400
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600
    - !type:OverallPlaytimeRequirement
      time: 93600
  weight: 10
  startingGear: HoSGear
  icon: "HeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-cc
  canBeAntag: false
  whitelistRequired: true
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Detective
  - External
  special:
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance
      flatBonus: 0.025

- type: startingGear
  id: HoSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
