using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SimpleStation14.Examine.SpriteExamine.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SpriteExamineWindow : FancyWindow
    {
        public GridContainer _spriteContainer => SpriteContainer;

        public SpriteExamineWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateUi(EntityUid Examined)
        {
            if (!IoCManager.Resolve<IEntityManager>().TryGetComponent<SpriteComponent>(Examined, out var sprite)) return;

            _spriteContainer.RemoveAllChildren();

            _spriteContainer.AddChild(new SpriteView
            {
                Sprite = sprite,
                Scale = (8, 8),
                OverrideDirection = Direction.South,
                Margin = new Thickness(8, 8, 8, 8),
            });

            _spriteContainer.AddChild(new SpriteView
            {
                Sprite = sprite,
                Scale = (8, 8),
                OverrideDirection = Direction.North,
                Margin = new Thickness(8, 8, 8, 8),
            });

            _spriteContainer.AddChild(new SpriteView
            {
                Sprite = sprite,
                Scale = (8, 8),
                OverrideDirection = Direction.West,
                Margin = new Thickness(8, 8, 8, 8),
            });

            _spriteContainer.AddChild(new SpriteView
            {
                Sprite = sprite,
                Scale = (8, 8),
                OverrideDirection = Direction.East,
                Margin = new Thickness(8, 8, 8, 8),
            });
        }
    }
}
