using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Utility;

namespace Content.Client.SimpleStation14.Skills;

[GenerateTypedNameReferences]
public sealed partial class SkillsUIContainer : PanelContainer
{
    public SkillsUIContainer()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetHeading(string desc)
    {
        Title.Text = desc;
    }

    public void SetDescription(string desc)
    {
        Description.SetMessage(desc);
    }

    public void SetColor(Color color)
    {
        Modulate = color;
    }
}
