- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "Boxer"
  supervisors: job-supervisors-hop
  setPreference: true
  access:
  - Service
  - Theatre
  special:
  - !type:AddComponentSpecial
    components:
    - type: Boxer
      modifiers:
        coefficients: #Remember these only apply to unarmed
          Blunt: 1.5
          Slash: 1.5
          Piercing: 1.5

- type: startingGear
  id: BoxerGear
  equipment:
    # jumpsuit: UniformShortsRed
    back: ClothingBackpackFilled
    belt: BoxerPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesBoxingRed
    shoes: ClothingShoesColorRed
  # innerclothingskirt: UniformShortsRedWithTop
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
  underpants: ClothingUnderboxers_assblastusa
  underpantsskirt: ClothingUnderboxers_assblastusa
  undershirt: Nothing
  undershirtskirt: ClothingUnderbra_binder
  undersocks: Nothing
