using Robust.Shared.Prototypes;
using Content.Shared.Kitchen;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Content.Client.SimpleStation14.Documentation.UI;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using System.Linq;

namespace Content.Client.SimpleStation14.Documentation.UI.Elements
{
    [GenerateTypedNameReferences]
    public sealed partial class FoodRecipeList : Control
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        // public BoxContainer FoodBoxes => FoodRecipeListb;

        public FoodRecipeList()
        {
            RobustXamlLoader.Load(this);

            // foreach (var recipe in _prototypeManager.EnumeratePrototypes<FoodRecipePrototype>())
            // {
            //     var foodBox = new BoxContainer() { Orientation = LayoutOrientation.Vertical };
            //     var food = _prototypeManager.Index<EntityPrototype>(recipe.Result);

            //     foodBox.AddChild(new Label() { Text = $"{food.Name}" });

            //     FoodBoxes.AddChild(foodBox);
            // }
        }
    }
}
