using Robust.Shared.Prototypes;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Content.Client.SimpleStation14.Documentation.UI;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using System.Linq;

namespace Content.Client.SimpleStation14.Documentation.UI.Elements
{
    [GenerateTypedNameReferences]
    public sealed partial class ReagentRecipeList : Control
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        // public BoxContainer ReagentBoxes => ReagentRecipeListb;

        public ReagentRecipeList()
        {
            RobustXamlLoader.Load(this);

            // foreach (var reaction in _prototypeManager.EnumeratePrototypes<ReactionPrototype>())
            // {
            //     var reagentBox = new BoxContainer() { Orientation = LayoutOrientation.Vertical };
            //     var reagent = _prototypeManager.Index<ReagentPrototype>(reaction.Result);

            //     reagentBox.AddChild(new Label() { Text = $"{reagent.Name}" });

            //     ReagentBoxes.AddChild(reagentBox);
            // }

            // foreach (var reagent in _prototypeManager.EnumeratePrototypes<ReagentPrototype>())
            // {
            //     var reagentBox = new BoxContainer() { Orientation = LayoutOrientation.Vertical };
            //     reagentBox.AddChild(new Label() { Text = $"reagent.Name" });

            //     ReagentBoxes.AddChild(reagentBox);
            // }
        }
    }
}
