using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.SimpleStation14.Documentation.UI.Elements
{
    [GenerateTypedNameReferences]
    public sealed partial class StandardOperatingProcedure : Control
    {

    }
}
