- type: job
  id: MedicalCyborg
  name: job-name-medical-cyborg
  description: job-description-cyborg
  playTimeTracker: JobCyborg
  whitelistRequired: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200
  icon: "MedicalCyborg"
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: PlayerCyborgMedical
  startingGear: CyborgGear # for char preview only
  canHaveTraits: false
