- type: job
  id: MedicalRobot
  name: job-name-medical-robot
  description: job-description-medical-robot
  playTimeTracker: JobCyborg
  whitelistRequired: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400
    - !type:OverallPlaytimeRequirement
      time: 28800
  icon: "MedicalCyborg"
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: PlayerRobotMedical
  startingGear: RobotGear # for char preview only
  canHaveTraits: false
