using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SimpleStation14.AI.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AICameraList : DefaultWindow
    {
        // public AICameraList()
        // {
        //     RobustXamlLoader.Load(this);
        // }
    }
}
