- type: job
  id: ClownCyborg
  name: job-name-clown-cyborg
  description: job-description-cyborg
  playTimeTracker: JobCyborg
  whitelistRequired: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
    - !type:RoleTimeRequirement
      role: JobClown
      time: 7200
  icon: "ClownCyborg"
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: PlayerCyborgClown
  startingGear: CyborgGear # for char preview only
  canHaveTraits: false
