- type: job
  id: JanitorCyborg
  name: job-name-janitor-cyborg
  description: job-description-cyborg
  playTimeTracker: JobCyborg
  whitelistRequired: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
    - !type:RoleTimeRequirement
      role: JobJanitor
      time: 7200
  icon: "JanitorCyborg"
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: PlayerCyborgJanitor
  startingGear: CyborgGear # for char preview only
  canHaveTraits: false
