using Robust.Shared.GameStates;

namespace Content.Shared.SimpleStation14.Holograms.Components;

/// <summary>
///     Marks that this Hologram requires a server of some kind to generate it.
/// </summary>
/// <remarks>
///     This could be anything from a literal server, to an AICore, to the person a HoloParasite lives in.
/// </remarks>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
public sealed partial class HologramServerLinkedComponent : Component
{
    /// <summary>
    ///     Whether this Hologram is bound to the same grid as its server.
    ///     If true, it will be returned if it leaves the grid.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    [DataField("gridBound"), AutoNetworkedField]
    [AutoNetworkedField]
    public bool GridBound = true;

    /// <summary>
    ///     The server that this hologram is generated by.
    /// </summary>
    /// <remarks>
    ///     This will be the lightbee if it's a lightbee hologram.
    /// </remarks>
    [ViewVariables(VVAccess.ReadOnly)]
    [AutoNetworkedField]
    [AutoNetworkedField]
    public EntityUid? LinkedServer;
}
