namespace Content.Shared.SimpleStation14.Holograms.Components;

/// <summary>
///     Marks that this Hologram requires a server of some kind to generate it.
/// </summary>
[RegisterComponent]
public sealed class HologramServerLinkedComponent : Component
{
    /// <summary>
    ///     Whether this Hologram is bound to the same grid as its server.
    ///     If false, it will be returned if it leaves the grid.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    [DataField("gridBound")]
    public bool GridBound = true;

    /// <summary>
    ///     The server that this hologram is generated by.
    /// </summary>
    /// <remarks>
    ///     This will be the lightbee if it's a lightbee hologram.
    /// </remarks>
    [ViewVariables(VVAccess.ReadOnly)]
    public EntityUid? LinkedServer;
}
