using System.Linq;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRespawnRulesWindow : DefaultWindow
    {
        public RichTextLabel RulesLabel => RespawnRulesLabel;
        public Button RespawnButton => ConfirmRespawnButton;

        public GhostRespawnRulesWindow()
        {
            RobustXamlLoader.Load(this);

            var message = new FormattedMessage();
            message.AddMarkup(Loc.GetString("ghost-respawn-rules-window-rules"));
            RulesLabel.SetMessage(message);

            RespawnButton.OnPressed += _ => {
                Close();
            };
        }
    }
}
