using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Content.Client.SimpleStation14.Documentation.UI;
using Content.Client.SimpleStation14.Documentation.UI.Elements;

namespace Content.Client.SimpleStation14.Documentation.UI.Pages
{
    [GenerateTypedNameReferences]
    public sealed partial class WikiPages : Control
    {
        public BoxContainer contents => Contents;
        public BoxContainer PlaceHolderContents => PlaceholderContents;

        public WikiPages()
        {
            RobustXamlLoader.Load(this);

            // PlaceHolderContents.AddChild(new FoodRecipeList());
            // PlaceHolderContents.AddChild(new ReagentRecipeList());
        }
    }
}
