name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "publish"

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Package
      run: |
        Tools/package_server_build.py -p win-x64 linux-x64 osx-x64 linux-arm64
        Tools/package_client_build.py

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"

    - name: Upload files to cdn
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
        host: ${{ secrets.PUBLISH_HOST }}
        port: ${{ secrets.PUBLISH_PORT }}
        user: ${{ secrets.PUBLISH_PUSH_USER }}
        key: ${{ secrets.PUBLISH_PUSH_KEY }}
        scp_options: -r -o StrictHostKeyChecking=no
        local: "release/${{ github.sha }}"
        remote: "builds"

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PUBLISH_HOST }}
        username: ${{ secrets.PUBLISH_NOTIFY_USER }}
        key: ${{ secrets.PUBLISH_NOTIFY_KEY }}
        port: ${{ secrets.PUBLISH_PORT }}
        script: /home/${{ secrets.PUBLISH_PUSH_USER }}/push.s1 ${{ github.sha }}

    - name: Publish changelog (Discord)
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

    - name: Publish changelog (RSS)
      run: Tools/actions_changelog_rss.py
      env:
        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
